### PR TITLE
WIP Falcon

### PR DESCRIPTION
**Pull request by stephaniewilkinson**

### CODE REVIEW

**Comment by stephaniewilkinson** [comment]
Here's what's happening on heroku:

```
2019-12-05T20:17:50.230856+00:00 heroku[web.1]: Starting process with command `falcon --threaded --count 4 -p "37361"`
2019-12-05T20:17:52.502362+00:00 app[web.1]: 0.26s     info: #<Falcon::Endpoint https://localhost:37361/ {:port=>37361}> [pid=4] [2019-12-05 20:17:52 +0000]
2019-12-05T20:17:52.502391+00:00 app[web.1]: | Falcon v0.34.4 taking flight! Using Async::Container::Threaded {:count=>4}
2019-12-05T20:17:52.502394+00:00 app[web.1]: | - To terminate: Ctrl-C or kill 4
2019-12-05T20:17:52.503073+00:00 app[web.1]: 0.27s     info: #<Async::Container::Threaded::Instance:0x00005642a48cad38> [pid=4] [2019-12-05 20:17:52 +0000]
2019-12-05T20:17:52.503076+00:00 app[web.1]: | - Per-process status: kill -USR1 4
2019-12-05T20:17:52.655616+00:00 app[web.1]: [Rollbar] Rollbar is disabled for Rake tasks since your Rake version is under 0.9.x. Please upgrade to 0.9.x or higher.
2019-12-05T20:17:52.658358+00:00 app[web.1]: [Rollbar] Rollbar is disabled for Rake tasks since your Rake version is under 0.9.x. Please upgrade to 0.9.x or higher.
2019-12-05T20:17:52.661239+00:00 app[web.1]: [Rollbar] Rollbar is disabled for Rake tasks since your Rake version is under 0.9.x. Please upgrade to 0.9.x or higher.
2019-12-05T20:18:37.049887+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
2019-12-05T20:18:37.049887+00:00 heroku[web.1]: Stopping process with SIGKILL
2019-12-05T20:18:37.171631+00:00 heroku[web.1]: Process exited with status 137
2019-12-05T20:18:50.426748+00:00 heroku[web.1]: State changed from starting to crashed
2019-12-05T20:18:50.431418+00:00 heroku[web.1]: State changed from crashed to starting
2019-12-05T20:18:50.325312+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
2019-12-05T20:18:50.325416+00:00 heroku[web.1]: Stopping process with SIGKILL
2019-12-05T20:18:50.411288+00:00 heroku[web.1]: Process exited with status 137
```

**Comment by stephaniewilkinson** [comment]
Latest error:
```
OpenSSL::SSL::SSLError: SSL_accept SYSCALL returned=5 errno=0 state=before SSL initialization

**Comment by ioquatix** [comment]
Did you figure it out?

**Comment by stephaniewilkinson** [comment]
Thanks for checking! Reordering the parameters fixed the port issue but I'm
still getting an SSL error.

**Comment by ioquatix** [comment]
Are you trying to use SSL?

Did you follow the example for Heroku?

https://github.com/socketry/utopia-falcon-heroku/blob/master/Procfile

**Comment by stephaniewilkinson** [comment]
@ioquatix I hadn't found that! Thanks so much for sharing!

**Comment by ioquatix** [comment]
No problem. Falcon binds to https by default. Eventually there will be a slightly different mode for production.

**Pull request merged**
